apiVersion: v1
kind: Pod
metadata:
  name: hytang1
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: nvidia.com/gpu.product
              operator: NotIn 
              values: ["1070", "1080", "M4000", "NVIDIA-GeForce-GTX-1080", "NVIDIA-GeForce-GTX-1070", "Quadro-M4000", "Tesla-K40c"]
  containers:
  - name: gpu-container
    image: gitlab-registry.nrp-nautilus.io/HYTang/proj1:b0164d23
    args: ["sleep", "infinity"]
    volumeMounts:
    - mountPath: /data
      name: data
    - mountPath: /dev/shm
      name: dshm
    resources:
      limits:
        memory: 8Gi
        nvidia.com/gpu: "1"
        cpu: "2"
      requests:
        memory: 8Gi
        nvidia.com/gpu: "1"
        cpu: "2"
  restartPolicy: Never
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: storage
    - name: dshm
      emptyDir:
        medium: Memory