name: Publish anibali/pytorch:1.8.1-cuda11.1-ubuntu20.04

on:
  push:
    branches:
    - master
    paths:
    - dockerfiles/1.8.1-cuda11.1-ubuntu20.04/*
    - .github/workflows/publish_1.8.1-cuda11.1-ubuntu20.04.yml
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: anibali/pytorch
        tags: 1.8.1-cuda11.1-ubuntu20.04,1.8.1-cuda11.1
        path: dockerfiles/1.8.1-cuda11.1-ubuntu20.04
